name: myconda
channels:
  - anaconda
  - conda-forge
  - defaults

dependencies:
  - python
  - gcc_linux-64
  - gxx_linux-64
  - cmake
  - maven
  - numpy
  - matplotlib
  - mysql
  - mysql-connector-python
  - redis
  - openjdk
  - nodejs
  - sqlite
  - go
  - kotlin
  