name: myconda
channels:
  - anaconda
  - nvidia/label/cuda-11.8.0
  - conda-forge
dependencies:
  - python=3.11
  - gcc_linux-64=9.5.0
  - gxx_linux-64=9.5.0
  - gcc=9.5.0
  - cudatoolkit=11.8.0
  - cuda=11.8.0
  - cmake=3.27
  - openjdk=17
  - nodejs=18
  - maven=3.9
  - numpy=1.26.2
  - matplotlib==3.8.2
  - mysql=8.4.0
  - mysql-connector-python=8.4.0
  - redis=5.0.3
  